### ISSUE TITLE
The dataset link is broken. Could you please provide other possible links?

### ISSUE THREAD

**Issue by AiliAili** [lancopku/AAPR#2]

**Comment by ypengc7512** [comment]
I just tried to download the dataset. The link is currently normal and the dataset can be downloaded. You can try a different browser to revisit the dataset link.

**Comment by AiliAili** [comment]
Thank you for your timely reply. Before the downloaded file is broken. Now it's normal. I'm closing the issue.

**Comment by poornima198m** [comment]
i have tried to run the code that is  provided and it says some file is missing like text_dict, abstract_train etc. could you please help to get those files.

**Comment by GabrielLin** [comment]
@ypengc7512  Could you help to solve the opening issues please? Thanks.
